[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Enable Netlify Identity and Git Gateway
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for admin access
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Enable Git Gateway for CMS
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
